version: '3'

services:
  mysql:
    image: mysql/mysql-server:5.7.28
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password

  cli:
    image: php:7.4-fpm
    container_name: cli
    volumes_from:
      - wordpress
    depends_on:
      - mysql
      - wordpress
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ~/wp-cli:/var/www/html
    restart: always
volumes:
  mysql_data:
  wordpress_data: