version: '3'

services:
  wp-mysql:
    build: mysql
    container_name: wp-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  wp-cli:
    build: cli
    container_name: wp-cli
    depends_on:
      - wp-mysql
    environment:
      WP_CLI_TEST_DBHOST: wp-mysql
    volumes:
      - ~/wp-cli:/home/cli/wp-cli
    restart: always