version: '3'

services:
  mysql:
    build: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  cli:
    build: cli
    container_name: cli
    depends_on:
      - mysql
    environment:
      WP_CLI_TEST_DBHOST: mysql
    volumes:
      - ~/wp-cli:/home/cli
    restart: always